In [29]:
import pandas as pd
from IPython.display import display

df_players = pd.read_csv("../data/raw/players.csv")
df_teams = pd.read_csv("../data/raw/teams.csv")
df_stats = pd.read_csv("../data/raw/season_stats_2025-26.csv")
df_rookies = pd.read_csv("../data/raw/rookies.csv")

display(df_players.head())
display(df_teams.head())
display(df_stats.head())
display(df_rookies.head())

display(df_players.shape)
display(df_teams.shape)
display(df_stats.shape)
display(df_rookies.shape)

display(df_stats.columns)

display(df_stats.describe())

display(df_stats[["PLAYER_NAME", "PTS", "AST", "REB", "FG_PCT", "FG3_PCT"]].head())

      id            full_name first_name     last_name  is_active
0  76001       Alaa Abdelnaby       Alaa     Abdelnaby      False
1  76002      Zaid Abdul-Aziz       Zaid    Abdul-Aziz      False
2  76003  Kareem Abdul-Jabbar     Kareem  Abdul-Jabbar      False
3     51   Mahmoud Abdul-Rauf    Mahmoud    Abdul-Rauf      False
4   1505    Tariq Abdul-Wahad      Tariq   Abdul-Wahad      False

,id,full_name,abbreviation,nickname,city,state,year_founded
0,1610612737,Atlanta Hawks,ATL,Hawks,Atlanta,Georgia,1949
1,1610612738,Boston Celtics,BOS,Celtics,Boston,Massachusetts,1946
2,1610612739,Cleveland Cavaliers,CLE,Cavaliers,Cleveland,Ohio,1970
3,1610612740,New Orleans Pelicans,NOP,Pelicans,New Orleans,Louisiana,2002
4,1610612741,Chicago Bulls,CHI,Bulls,Chicago,Illinois,1966

,Unnamed: 0,PLAYER_ID,PLAYER_NAME,NICKNAME,TEAM_ID,TEAM_ABBREVIATION,AGE,GP,W,L,...,BLKA_RANK,PF_RANK,PFD_RANK,PTS_RANK,PLUS_MINUS_RANK,NBA_FANTASY_PTS_RANK,DD2_RANK,TD3_RANK,WNBA_FANTASY_PTS_RANK,TEAM_COUNT
0,0,1630639,A.J. Lawson,A.J.,1610612761,TOR,25.0,24,12,12,...,445,439,450,445,286,481,284,38,467,1
1,1,1631260,AJ Green,AJ,1610612749,MIL,26.0,78,31,47,...,439,121,335,201,398,292,284,38,231,1
2,2,1642358,AJ Johnson,AJ,1610612742,DAL,21.0,48,9,39,...,178,520,456,475,339,502,284,38,501,2
3,3,203932,Aaron Gordon,Aaron,1610612743,DEN,30.0,36,27,9,...,254,274,66,88,12,113,114,38,111,1
4,4,1628988,Aaron Holiday,Aaron,1610612745,HOU,29.0,57,38,19,...,491,405,393,386,115,457,284,38,430,1

,PERSON_ID,PLAYER_NAME,SEASON,ROUND_NUMBER,ROUND_PICK,OVERALL_PICK,DRAFT_TYPE,TEAM_ID,TEAM_CITY,TEAM_NAME,TEAM_ABBREVIATION,ORGANIZATION,ORGANIZATION_TYPE,PLAYER_PROFILE_FLAG
0,1642843,Cooper Flagg,2025,1,1,1,Draft,1610612742,Dallas,Mavericks,DAL,Duke,College/University,1
1,1642844,Dylan Harper,2025,1,2,2,Draft,1610612759,San Antonio,Spurs,SAS,Rutgers,College/University,1
2,1642845,VJ Edgecombe,2025,1,3,3,Draft,1610612755,Philadelphia,76ers,PHI,Baylor,College/University,1
3,1642851,Kon Knueppel,2025,1,4,4,Draft,1610612766,Charlotte,Hornets,CHA,Duke,College/University,1
4,1642846,Ace Bailey,2025,1,5,5,Draft,1610612762,Utah,Jazz,UTA,Rutgers,College/University,1

(5103, 5)

(30, 7)

(582, 68)

(8374, 14)

Index(['Unnamed: 0', 'PLAYER_ID', 'PLAYER_NAME', 'NICKNAME', 'TEAM_ID',
       'TEAM_ABBREVIATION', 'AGE', 'GP', 'W', 'L', 'W_PCT', 'MIN', 'FGM',
       'FGA', 'FG_PCT', 'FG3M', 'FG3A', 'FG3_PCT', 'FTM', 'FTA', 'FT_PCT',
       'OREB', 'DREB', 'REB', 'AST', 'TOV', 'STL', 'BLK', 'BLKA', 'PF', 'PFD',
       'PTS', 'PLUS_MINUS', 'NBA_FANTASY_PTS', 'DD2', 'TD3',
       'WNBA_FANTASY_PTS', 'GP_RANK', 'W_RANK', 'L_RANK', 'W_PCT_RANK',
       'MIN_RANK', 'FGM_RANK', 'FGA_RANK', 'FG_PCT_RANK', 'FG3M_RANK',
       'FG3A_RANK', 'FG3_PCT_RANK', 'FTM_RANK', 'FTA_RANK', 'FT_PCT_RANK',
       'OREB_RANK', 'DREB_RANK', 'REB_RANK', 'AST_RANK', 'TOV_RANK',
       'STL_RANK', 'BLK_RANK', 'BLKA_RANK', 'PF_RANK', 'PFD_RANK', 'PTS_RANK',
       'PLUS_MINUS_RANK', 'NBA_FANTASY_PTS_RANK', 'DD2_RANK', 'TD3_RANK',
       'WNBA_FANTASY_PTS_RANK', 'TEAM_COUNT'],
      dtype='str')

,Unnamed: 0,PLAYER_ID,TEAM_ID,AGE,GP,W,L,W_PCT,MIN,FGM,...,BLKA_RANK,PF_RANK,PFD_RANK,PTS_RANK,PLUS_MINUS_RANK,NBA_FANTASY_PTS_RANK,DD2_RANK,TD3_RANK,WNBA_FANTASY_PTS_RANK,TEAM_COUNT
count,582.000000,5.820000e+02,5.820000e+02,582.000000,582.000000,582.000000,582.000000,582.000000,582.000000,582.000000,...,582.000000,582.000000,582.000000,582.000000,582.000000,582.000000,582.000000,582.000000,582.000000,582.000000
mean,290.500000,1.476871e+06,1.610613e+09,26.309278,45.792096,23.075601,22.716495,0.482864,19.666667,3.325601,...,288.955326,291.029210,290.991409,291.345361,291.374570,291.493127,206.018900,36.525773,291.431271,1.135739
std,168.153204,4.499530e+05,8.755817e+00,4.217072,24.937300,16.130101,14.192324,0.204835,8.912369,2.254278,...,165.499259,167.845703,167.720215,168.004946,168.132951,168.146110,92.249967,5.996142,168.074643,0.380860
min,0.000000,2.544000e+03,1.610613e+09,19.000000,1.000000,0.000000,0.000000,0.000000,1.500000,0.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
25%,145.250000,1.629018e+06,1.610613e+09,23.000000,23.000000,9.000000,11.000000,0.317250,12.300000,1.600000,...,146.250000,146.250000,146.250000,146.250000,146.250000,146.250000,128.000000,38.000000,146.250000,1.000000
50%,290.500000,1.630694e+06,1.610613e+09,25.000000,51.000000,21.500000,23.000000,0.514000,20.000000,2.950000,...,289.000000,291.000000,290.500000,291.500000,291.500000,291.500000,284.000000,38.000000,291.500000,1.000000
75%,435.750000,1.641838e+06,1.610613e+09,28.000000,67.750000,37.000000,33.000000,0.632750,27.100000,4.600000,...,436.750000,436.750000,433.000000,436.750000,436.750000,436.750000,284.000000,38.000000,436.750000,1.000000
max,581.000000,1.643257e+06,1.610613e+09,41.000000,82.000000,62.000000,65.000000,1.000000,38.000000,10.800000,...,540.000000,579.000000,571.000000,579.000000,582.000000,582.000000,284.000000,38.000000,582.000000,4.000000

     PLAYER_NAME   PTS  AST  REB  FG_PCT  FG3_PCT
0    A.J. Lawson   4.2  0.3  1.8   0.436    0.422
1       AJ Green  10.4  1.9  2.7   0.424    0.419
2     AJ Johnson   3.3  1.0  1.1   0.324    0.211
3   Aaron Gordon  16.2  2.7  5.8   0.497    0.389
4  Aaron Holiday   5.5  1.1  1.0   0.417    0.394

In [30]:
display(df_players['is_active'].value_counts())

active_players = df_players[df_players['is_active'] == True]
display(active_players.head())

display(len(active_players))

display(df_players[['full_name', 'id']].head(20))

display(df_players['full_name'].value_counts().head())

display(df_stats[['PLAYER_NAME', 'TEAM_ID', 'TEAM_ABBREVIATION']].head())

is_active
False    4573
True      530
Name: count, dtype: int64

         id         full_name first_name last_name  is_active
10  1630173  Precious Achiuwa   Precious   Achiuwa       True
22   203500      Steven Adams     Steven     Adams       True
24  1628389       Bam Adebayo        Bam   Adebayo       True
29  1630534      Ochai Agbaji      Ochai    Agbaji       True
41  1630583      Santi Aldama      Santi    Aldama       True

530

              full_name       id
0        Alaa Abdelnaby    76001
1       Zaid Abdul-Aziz    76002
2   Kareem Abdul-Jabbar    76003
3    Mahmoud Abdul-Rauf       51
4     Tariq Abdul-Wahad     1505
5   Shareef Abdur-Rahim      949
6         Tom Abernethy    76005
7           Forest Able    76006
8        John Abramovic    76007
9          Alex Abrines   203518
10     Precious Achiuwa  1630173
11           Alex Acker   101165
12      Donald Ackerman    76008
13           Mark Acres    76009
14        Charles Acton    76010
15           Quincy Acy   203112
16          Alvan Adams    76011
17            Don Adams    76012
18         Hassan Adams   200801
19         Jaylen Adams  1629121

full_name
George Johnson    3
Charles Smith     3
Dee Brown         2
Charlie Davis     2
Johnny Davis      2
Name: count, dtype: int64

     PLAYER_NAME     TEAM_ID TEAM_ABBREVIATION
0    A.J. Lawson  1610612761               TOR
1       AJ Green  1610612749               MIL
2     AJ Johnson  1610612742               DAL
3   Aaron Gordon  1610612743               DEN
4  Aaron Holiday  1610612745               HOU

In [31]:
display(df_teams.head())
display(df_teams.columns)

display(len(df_teams))

display(df_teams[['city', 'nickname', 'abbreviation']].head())

display(df_teams.sort_values('city').head(10))

display(df_teams[['id', 'full_name']].head())

,id,full_name,abbreviation,nickname,city,state,year_founded
0,1610612737,Atlanta Hawks,ATL,Hawks,Atlanta,Georgia,1949
1,1610612738,Boston Celtics,BOS,Celtics,Boston,Massachusetts,1946
2,1610612739,Cleveland Cavaliers,CLE,Cavaliers,Cleveland,Ohio,1970
3,1610612740,New Orleans Pelicans,NOP,Pelicans,New Orleans,Louisiana,2002
4,1610612741,Chicago Bulls,CHI,Bulls,Chicago,Illinois,1966

Index(['id', 'full_name', 'abbreviation', 'nickname', 'city', 'state',
       'year_founded'],
      dtype='str')

30

          city   nickname abbreviation
0      Atlanta      Hawks          ATL
1       Boston    Celtics          BOS
2    Cleveland  Cavaliers          CLE
3  New Orleans   Pelicans          NOP
4      Chicago      Bulls          CHI

,id,full_name,abbreviation,nickname,city,state,year_founded
0,1610612737,Atlanta Hawks,ATL,Hawks,Atlanta,Georgia,1949
1,1610612738,Boston Celtics,BOS,Celtics,Boston,Massachusetts,1946
14,1610612751,Brooklyn Nets,BKN,Nets,Brooklyn,New York,1976
29,1610612766,Charlotte Hornets,CHA,Hornets,Charlotte,North Carolina,1988
4,1610612741,Chicago Bulls,CHI,Bulls,Chicago,Illinois,1966
2,1610612739,Cleveland Cavaliers,CLE,Cavaliers,Cleveland,Ohio,1970
5,1610612742,Dallas Mavericks,DAL,Mavericks,Dallas,Texas,1980
6,1610612743,Denver Nuggets,DEN,Nuggets,Denver,Colorado,1976
28,1610612765,Detroit Pistons,DET,Pistons,Detroit,Michigan,1948
8,1610612745,Houston Rockets,HOU,Rockets,Houston,Texas,1967

           id             full_name
0  1610612737         Atlanta Hawks
1  1610612738        Boston Celtics
2  1610612739   Cleveland Cavaliers
3  1610612740  New Orleans Pelicans
4  1610612741         Chicago Bulls

In [32]:
df_stats['TOTAL_3PA'] = df_stats['FG3A'] * df_stats['GP']
df_active = df_stats[df_stats['GP'] > 0]
team_3pa = df_active.groupby('TEAM_ABBREVIATION')['TOTAL_3PA'].sum().reset_index()
display(team_3pa.sort_values('TOTAL_3PA', ascending=False).head(10))

df_stats['TOTAL_MIN'] = df_stats['MIN'] * df_stats['GP']
display(df_stats[['PLAYER_NAME', 'MIN', 'GP', 'TOTAL_MIN']].sort_values('TOTAL_MIN', ascending=False).head(10))

   TEAM_ABBREVIATION  TOTAL_3PA
24               POR     3674.0
3                CHA     3591.3
5                CLE     3566.5
0                ATL     3548.8
9                GSW     3451.0
23               PHX     3376.3
16               MIL     3349.7
19               NYK     3297.6
17               MIN     3264.5
2                BOS     3254.2

          PLAYER_NAME   MIN  GP  TOTAL_MIN
21      Amen Thompson  37.4  79     2954.6
333      Kevin Durant  36.4  78     2839.2
145      Desmond Bane  33.6  82     2755.2
530    Toumani Camara  33.3  82     2730.6
218  Jabari Smith Jr.  35.1  77     2702.7
400     Mikal Bridges  32.8  82     2689.6
496    Scottie Barnes  33.5  80     2680.0
554      Tyrese Maxey  38.0  70     2660.0
242      Jamal Murray  35.4  75     2655.0
144     Derrick White  34.1  77     2625.7

In [33]:
df_rookies_2025 = df_rookies[df_rookies['SEASON'] == 2025]

df_rookie_stats = df_stats.merge(
    df_rookies_2025[['PERSON_ID', 'PLAYER_NAME']],
    left_on='PLAYER_ID',
    right_on='PERSON_ID',
    how='inner'
)

df_rookie_stats[['PLAYER_NAME_x', 'REB', 'GP']].sort_values('REB', ascending=False).head(10)

           PLAYER_NAME_x  REB  GP
35        Maxime Raynaud  7.5  74
13           Derik Queen  7.1  81
11          Cooper Flagg  6.7  70
8          Cedric Coward  5.9  62
49          VJ Edgecombe  5.6  75
44      Ryan Kalkbrenner  5.5  69
31          Kon Knueppel  5.3  81
10  Collin Murray-Boyles  5.0  57
12            Danny Wolf  4.9  57
0             Ace Bailey  4.2  72

In [34]:
df_stats['PTS_TOTAL'] = df_stats['PTS'] * df_stats['GP']
df_stats['FGA_TOTAL'] = df_stats['FGA'] * df_stats['GP']
df_stats['FTA_TOTAL'] = df_stats['FTA'] * df_stats['GP']
df_stats['TOV_TOTAL'] = df_stats['TOV'] * df_stats['GP']
df_stats['OREB_TOTAL'] = df_stats['OREB'] * df_stats['GP']

df_stats['POSS'] = df_stats['FGA_TOTAL'] + 0.44 * df_stats['FTA_TOTAL'] + df_stats['TOV_TOTAL'] - df_stats['OREB_TOTAL']

df_team = df_stats.groupby('TEAM_ABBREVIATION').agg({
    'PTS_TOTAL': 'sum',
    'POSS': 'sum'
}).reset_index()

df_team['ORTG'] = (df_team['PTS_TOTAL'] / df_team['POSS']) * 100

df_team.sort_values('ORTG', ascending=False).head(10)

   TEAM_ABBREVIATION  PTS_TOTAL      POSS        ORTG
7                DEN    10272.7  8642.584  118.861442
2                BOS     9304.3  7857.380  118.414790
26               SAS     9748.4  8277.768  117.766045
19               NYK     9881.5  8412.704  117.459262
13               LAL     9767.0  8344.412  117.048391
20               OKC     9840.7  8441.204  116.579341
17               MIN    10455.1  9003.352  116.124528
3                CHA     9409.0  8109.644  116.022356
5                CLE    10616.5  9162.312  115.871409
10               HOU     9458.1  8165.072  115.836088

In [35]:
display(df_stats.head())
display(df_stats.columns)
display(df_stats.describe())

display(df_stats[['PLAYER_NAME', 'PTS']].sort_values('PTS', ascending=False).head(10))

display(df_stats[['PLAYER_NAME', 'REB']].sort_values('REB', ascending=False).head(10))

display(df_stats[['PLAYER_NAME', 'AST']].sort_values('AST', ascending=False).head(10))

df_filtered = df_stats.copy()
df_filtered = df_filtered[df_filtered['FGA'] >= 10]
display(df_filtered[['PLAYER_NAME', 'FGA', 'FG_PCT']].sort_values('FG_PCT', ascending=False).head(10))


display(df_stats[['PLAYER_NAME', 'MIN', 'GP']].sort_values('MIN', ascending=False).head(10))

,Unnamed: 0,PLAYER_ID,PLAYER_NAME,NICKNAME,TEAM_ID,TEAM_ABBREVIATION,AGE,GP,W,L,...,WNBA_FANTASY_PTS_RANK,TEAM_COUNT,TOTAL_3PA,TOTAL_MIN,PTS_TOTAL,FGA_TOTAL,FTA_TOTAL,TOV_TOTAL,OREB_TOTAL,POSS
0,0,1630639,A.J. Lawson,A.J.,1610612761,TOR,25.0,24,12,12,...,467,1,45.6,225.6,100.8,79.2,19.2,7.2,9.6,85.248
1,1,1631260,AJ Green,AJ,1610612749,MIL,26.0,78,31,47,...,231,1,553.8,2269.8,811.2,616.2,62.4,78.0,31.2,690.456
2,2,1642358,AJ Johnson,AJ,1610612742,DAL,21.0,48,9,39,...,501,2,57.6,451.2,158.4,177.6,38.4,28.8,14.4,208.896
3,3,203932,Aaron Gordon,Aaron,1610612743,DEN,30.0,36,27,9,...,111,1,158.4,1004.4,583.2,399.6,162.0,39.6,50.4,460.080
4,4,1628988,Aaron Holiday,Aaron,1610612745,HOU,29.0,57,38,19,...,430,1,171.0,780.9,313.5,250.8,39.9,39.9,11.4,296.856

Index(['Unnamed: 0', 'PLAYER_ID', 'PLAYER_NAME', 'NICKNAME', 'TEAM_ID',
       'TEAM_ABBREVIATION', 'AGE', 'GP', 'W', 'L', 'W_PCT', 'MIN', 'FGM',
       'FGA', 'FG_PCT', 'FG3M', 'FG3A', 'FG3_PCT', 'FTM', 'FTA', 'FT_PCT',
       'OREB', 'DREB', 'REB', 'AST', 'TOV', 'STL', 'BLK', 'BLKA', 'PF', 'PFD',
       'PTS', 'PLUS_MINUS', 'NBA_FANTASY_PTS', 'DD2', 'TD3',
       'WNBA_FANTASY_PTS', 'GP_RANK', 'W_RANK', 'L_RANK', 'W_PCT_RANK',
       'MIN_RANK', 'FGM_RANK', 'FGA_RANK', 'FG_PCT_RANK', 'FG3M_RANK',
       'FG3A_RANK', 'FG3_PCT_RANK', 'FTM_RANK', 'FTA_RANK', 'FT_PCT_RANK',
       'OREB_RANK', 'DREB_RANK', 'REB_RANK', 'AST_RANK', 'TOV_RANK',
       'STL_RANK', 'BLK_RANK', 'BLKA_RANK', 'PF_RANK', 'PFD_RANK', 'PTS_RANK',
       'PLUS_MINUS_RANK', 'NBA_FANTASY_PTS_RANK', 'DD2_RANK', 'TD3_RANK',
       'WNBA_FANTASY_PTS_RANK', 'TEAM_COUNT', 'TOTAL_3PA', 'TOTAL_MIN',
       'PTS_TOTAL', 'FGA_TOTAL', 'FTA_TOTAL', 'TOV_TOTAL', 'OREB_TOTAL',
       'POSS'],
      dtype='str')

,Unnamed: 0,PLAYER_ID,TEAM_ID,AGE,GP,W,L,W_PCT,MIN,FGM,...,WNBA_FANTASY_PTS_RANK,TEAM_COUNT,TOTAL_3PA,TOTAL_MIN,PTS_TOTAL,FGA_TOTAL,FTA_TOTAL,TOV_TOTAL,OREB_TOTAL,POSS
count,582.000000,5.820000e+02,5.820000e+02,582.000000,582.000000,582.000000,582.000000,582.000000,582.000000,582.000000,...,582.000000,582.000000,582.000000,582.000000,582.000000,582.000000,582.000000,582.00000,582.000000,582.000000
mean,290.500000,1.476871e+06,1.610613e+09,26.309278,45.792096,23.075601,22.716495,0.482864,19.666667,3.325601,...,291.431271,1.135739,156.278351,1019.754467,488.802577,376.553436,99.286254,58.32732,48.166323,430.400385
std,168.153204,4.499530e+05,8.755817e+00,4.217072,24.937300,16.130101,14.192324,0.204835,8.912369,2.254278,...,168.074643,0.380860,155.925578,771.938125,459.901128,340.983912,114.966254,54.95378,51.402570,414.833085
min,0.000000,2.544000e+03,1.610613e+09,19.000000,1.000000,0.000000,0.000000,0.000000,1.500000,0.000000,...,1.000000,1.000000,0.000000,2.700000,0.000000,1.000000,0.000000,0.00000,0.000000,0.000000
25%,145.250000,1.629018e+06,1.610613e+09,23.000000,23.000000,9.000000,11.000000,0.317250,12.300000,1.600000,...,146.250000,1.000000,22.125000,293.250000,107.175000,92.550000,17.600000,13.57500,10.800000,92.176000
50%,290.500000,1.630694e+06,1.610613e+09,25.000000,51.000000,21.500000,23.000000,0.514000,20.000000,2.950000,...,291.500000,1.000000,114.000000,940.300000,363.300000,292.300000,61.500000,42.30000,32.650000,298.328000
75%,435.750000,1.641838e+06,1.610613e+09,28.000000,67.750000,37.000000,33.000000,0.632750,27.100000,4.600000,...,436.750000,1.000000,246.000000,1608.600000,759.000000,579.075000,130.950000,85.65000,64.875000,653.312000
max,581.000000,1.643257e+06,1.610613e+09,41.000000,82.000000,62.000000,65.000000,1.000000,38.000000,10.800000,...,582.000000,4.000000,741.600000,2954.600000,2144.000000,1540.700000,646.400000,256.00000,346.500000,1961.216000

                 PLAYER_NAME   PTS
372              Luka Dončić  33.5
501  Shai Gilgeous-Alexander  31.1
31           Anthony Edwards  28.8
260             Jaylen Brown  28.7
554             Tyrese Maxey  28.3
154         Donovan Mitchell  27.9
320            Kawhi Leonard  27.9
429             Nikola Jokić  27.7
186    Giannis Antetokounmpo  27.6
279              Joel Embiid  26.9

            PLAYER_NAME   REB
429        Nikola Jokić  12.9
317  Karl-Anthony Towns  11.9
153     Donovan Clingan  11.6
559   Victor Wembanyama  11.5
483         Rudy Gobert  11.5
151    Domantas Sabonis  11.4
576           Zach Edey  11.1
30        Anthony Davis  11.1
563      Walker Kessler  10.8
214         Ivica Zubac  10.6

         PLAYER_NAME   AST
429     Nikola Jokić  10.7
71   Cade Cunningham   9.9
299      Josh Giddey   9.1
372      Luka Dončić   8.3
216        Ja Morant   8.1
245     James Harden   8.0
531       Trae Young   8.0
234    Jalen Johnson   7.9
26   Andrew Nembhard   7.7
510   Stephon Castle   7.4

                 PLAYER_NAME   FGA  FG_PCT
232              Jalen Duren  11.5   0.650
186    Giannis Antetokounmpo  16.6   0.624
580          Zion Williamson  13.0   0.600
214              Ivica Zubac  10.0   0.598
429             Nikola Jokić  17.4   0.569
88             Chet Holmgren  11.3   0.557
501  Shai Gilgeous-Alexander  19.4   0.553
177              Evan Mobley  13.2   0.546
151         Domantas Sabonis  11.6   0.543
21             Amen Thompson  13.2   0.534

          PLAYER_NAME   MIN  GP
554      Tyrese Maxey  38.0  70
21      Amen Thompson  37.4  79
333      Kevin Durant  36.4  78
526        Toby Okani  36.2   6
372       Luka Dončić  35.8  64
542   Trey Murphy III  35.5  66
242      Jamal Murray  35.4  75
234     Jalen Johnson  35.2  72
218  Jabari Smith Jr.  35.1  77
31    Anthony Edwards  35.0  61