In [17]:
from nba_api.stats.static import players
import pandas as pd

df_players = pd.DataFrame(players.get_players())
df_players.to_csv("../data/raw/players.csv", index=False)
df_players.head()

      id            full_name first_name     last_name  is_active
0  76001       Alaa Abdelnaby       Alaa     Abdelnaby      False
1  76002      Zaid Abdul-Aziz       Zaid    Abdul-Aziz      False
2  76003  Kareem Abdul-Jabbar     Kareem  Abdul-Jabbar      False
3     51   Mahmoud Abdul-Rauf    Mahmoud    Abdul-Rauf      False
4   1505    Tariq Abdul-Wahad      Tariq   Abdul-Wahad      False

In [18]:
from nba_api.stats.static import teams

df_teams = pd.DataFrame(teams.get_teams())
df_teams.to_csv("../data/raw/teams.csv", index=False)
df_teams.head()

,id,full_name,abbreviation,nickname,city,state,year_founded
0,1610612737,Atlanta Hawks,ATL,Hawks,Atlanta,Georgia,1949
1,1610612738,Boston Celtics,BOS,Celtics,Boston,Massachusetts,1946
2,1610612739,Cleveland Cavaliers,CLE,Cavaliers,Cleveland,Ohio,1970
3,1610612740,New Orleans Pelicans,NOP,Pelicans,New Orleans,Louisiana,2002
4,1610612741,Chicago Bulls,CHI,Bulls,Chicago,Illinois,1966

In [19]:
from nba_api.stats.endpoints import leaguedashplayerstats

stats = leaguedashplayerstats.LeagueDashPlayerStats(
    season="2025-26",
    season_type_all_star="Regular Season",
    per_mode_detailed="PerGame"
)

df_stats = stats.get_data_frames()[0]
df_stats.to_csv("../data/raw/season_stats_2025-26.csv")
df_stats.head()

,PLAYER_ID,PLAYER_NAME,NICKNAME,TEAM_ID,TEAM_ABBREVIATION,AGE,GP,W,L,W_PCT,...,BLKA_RANK,PF_RANK,PFD_RANK,PTS_RANK,PLUS_MINUS_RANK,NBA_FANTASY_PTS_RANK,DD2_RANK,TD3_RANK,WNBA_FANTASY_PTS_RANK,TEAM_COUNT
0,1630639,A.J. Lawson,A.J.,1610612761,TOR,25.0,24,12,12,0.500,...,445,439,450,445,286,481,284,38,467,1
1,1631260,AJ Green,AJ,1610612749,MIL,26.0,78,31,47,0.397,...,439,121,335,201,398,292,284,38,231,1
2,1642358,AJ Johnson,AJ,1610612742,DAL,21.0,48,9,39,0.188,...,178,520,456,475,339,502,284,38,501,2
3,203932,Aaron Gordon,Aaron,1610612743,DEN,30.0,36,27,9,0.750,...,254,274,66,88,12,113,114,38,111,1
4,1628988,Aaron Holiday,Aaron,1610612745,HOU,29.0,57,38,19,0.667,...,491,405,393,386,115,457,284,38,430,1