In [12]:
from nba_api.stats.static import players
import pandas as pd

df_players = pd.DataFrame(players.get_players())
df_players.to_csv("../data/raw/players.csv", index=False)
df_players.head()

      id            full_name first_name     last_name  is_active
0  76001       Alaa Abdelnaby       Alaa     Abdelnaby      False
1  76002      Zaid Abdul-Aziz       Zaid    Abdul-Aziz      False
2  76003  Kareem Abdul-Jabbar     Kareem  Abdul-Jabbar      False
3     51   Mahmoud Abdul-Rauf    Mahmoud    Abdul-Rauf      False
4   1505    Tariq Abdul-Wahad      Tariq   Abdul-Wahad      False

In [13]:
from nba_api.stats.static import teams

df_teams = pd.DataFrame(teams.get_teams())
df_teams.to_csv("../data/raw/teams.csv", index=False)
df_teams.head()

,id,full_name,abbreviation,nickname,city,state,year_founded
0,1610612737,Atlanta Hawks,ATL,Hawks,Atlanta,Georgia,1949
1,1610612738,Boston Celtics,BOS,Celtics,Boston,Massachusetts,1946
2,1610612739,Cleveland Cavaliers,CLE,Cavaliers,Cleveland,Ohio,1970
3,1610612740,New Orleans Pelicans,NOP,Pelicans,New Orleans,Louisiana,2002
4,1610612741,Chicago Bulls,CHI,Bulls,Chicago,Illinois,1966

In [ ]:
from nba_api.stats.endpoints import leaguedashplayerstats

stats = leaguedashplayerstats.LeagueDashPlayerStats(
    season="2025-26",
    season_type_all_star="Regular Season",
    per_mode_detailed="PerGame"
)

df_stats = stats.get_data_frames()[0]
df_stats.to_csv("../data/raw/season_stats_2025-26.csv")
df_stats.head()

ReadTimeout: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=30)

In [ ]:
from nba_api.stats.endpoints import drafthistory

# Pull full draft history
dh = drafthistory.DraftHistory(league_id='00')
df_draft = dh.get_data_frames()[0]

df_draft.to_csv("../data/raw/rookies.csv", index=False)
df_draft.head(10)

,PERSON_ID,PLAYER_NAME,SEASON,ROUND_NUMBER,ROUND_PICK,OVERALL_PICK,DRAFT_TYPE,TEAM_ID,TEAM_CITY,TEAM_NAME,TEAM_ABBREVIATION,ORGANIZATION,ORGANIZATION_TYPE,PLAYER_PROFILE_FLAG
0,1642843,Cooper Flagg,2025,1,1,1,Draft,1610612742,Dallas,Mavericks,DAL,Duke,College/University,1
1,1642844,Dylan Harper,2025,1,2,2,Draft,1610612759,San Antonio,Spurs,SAS,Rutgers,College/University,1
2,1642845,VJ Edgecombe,2025,1,3,3,Draft,1610612755,Philadelphia,76ers,PHI,Baylor,College/University,1
3,1642851,Kon Knueppel,2025,1,4,4,Draft,1610612766,Charlotte,Hornets,CHA,Duke,College/University,1
4,1642846,Ace Bailey,2025,1,5,5,Draft,1610612762,Utah,Jazz,UTA,Rutgers,College/University,1
5,1642848,Tre Johnson,2025,1,6,6,Draft,1610612764,Washington,Wizards,WAS,Texas,College/University,1
6,1642847,Jeremiah Fears,2025,1,7,7,Draft,1610612740,New Orleans,Pelicans,NOP,Oklahoma,College/University,1
7,1642856,Egor Dëmin,2025,1,8,8,Draft,1610612751,Brooklyn,Nets,BKN,Brigham Young,College/University,1
8,1642867,Collin Murray-Boyles,2025,1,9,9,Draft,1610612761,Toronto,Raptors,TOR,South Carolina,College/University,1
9,1642863,Khaman Maluach,2025,1,10,10,Draft,1610612745,Houston,Rockets,HOU,Duke,College/University,1